### PR TITLE
feat: support deno and modern chromium

### PR DESCRIPTION
**Pull request by idanran**

### CODE REVIEW

**Comment by idanran** [comment]
PTAL @sindresorhus

**Comment by sindresorhus** [comment]
Deno supports Node.js packages. We are not going to add lots of custom code for Deno.

**Comment by sindresorhus** [comment]
As for the Firefox support, can you link to a source that documents the support for ANSI escapes?

**Comment by idanran** [comment]
> Deno supports Node.js packages. We are not going to add lots of custom code for Deno.

But the polyfill it introduces automatically can cause unnecessary privileges to be requested. And it also reduces the speed of starting work.
image
image

**Comment by idanran** [comment]
> As for the Firefox support, can you link to a source that documents the support for ANSI escapes?

It really doesn't support ASNI, which I was wrong about. I will fix it.

**Comment by sindresorhus** [comment]
> But the polyfill it introduces automatically can cause unnecessary privileges to be requested.

You should open an issue on Deno about that. This sounds like a bug in the polyfill.

**Comment by idanran** [comment]
> > But the polyfill it introduces automatically can cause unnecessary privileges to be requested.
> 
> You should open an issue on Deno about that. This sounds like a bug in the polyfill.

I'm not sure if this is a bug, but I can confirm that introducing polyfill slows down startup.

**Comment by idanran** [comment]
> > But the polyfill it introduces automatically can cause unnecessary privileges to be requested.
> 
> You should open an issue on Deno about that. This sounds like a bug in the polyfill.

This is not a bug in polyfill.

**Comment by Qix-** [comment]
Not a huge fan of this. For years javascript standards have diverged creating hell on earth for package maintainers. This seems to be multiplicative maintenance overhead...

**Comment by idanran** [comment]
> Not a huge fan of this. For years javascript standards have diverged creating hell on earth for package maintainers. This seems to be multiplicative maintenance overhead...

I will open a PR later to rework it. I believe we can solve this problem.

**Comment by idanran** [comment]
> Not a huge fan of this. For years javascript standards have diverged creating hell on earth for package maintainers. This seems to be multiplicative maintenance overhead...

See #142

**Pull request closed without merging**
