### PR TITLE
Add support for Gitea Actions

### PR DESCRIPTION
**Pull request by silverwind**
Add support for [Gitea Actions](https://docs.gitea.com/1.20/usage/actions/overview).

Both [`GITHUB_ACTIONS`](https://gitea.com/gitea/act/src/commit/a165e17878fddd3d3b80ccb6fccc653bcfc0cbbb/pkg/runner/run_context.go#L943) and [`GITEA_ACTIONS`](https://gitea.com/gitea/act_runner/src/commit/ec38401097a1cbe02cc1f029436f514740054a82/internal/app/run/runner.go#L75) are present, with the former being a compatibilty solution, the latter is the true identifier.

It [supports](https://github.com/go-gitea/gitea/issues/24777) 16 colors and true color, but not 256 color currently. I plan to fix 256 color and will follow up here once it's done.

### CODE REVIEW

**Comment by silverwind** [comment]
The `xo` failure seems unrelated.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/25401 adds 256 color support so everything up to true color is supported and the condition is simplified.

**Comment by silverwind** [comment]
Tried updating `xo`, and that seems to at least not make it crash anymore. Locally it outputs a number of issues. All are unrelated to this PR:

```
  index.js:60:1
  ⚠  60:1   Function _supportsColor has a complexity of 37. Maximum allowed is 20.                            complexity

  test.js:24:1
  ⚠  24:1   Unexpected fixme comment: FIXME.                                                                  no-warning-comments

  index.d.ts:3:18
  ✖   3:18  Use a type instead of an interface.                                                               @typescript-eslint/consistent-type-definitions
  ✖  24:18  Use a type instead of an interface.                                                               @typescript-eslint/consistent-type-definitions

  browser.js:6:12
  ✖   6:12  Optional chainings are not supported until Node.js 14.0.0. The configured version range is >=12.  n/no-unsupported-features/es-syntax

  index.test-d.ts:3:1
  ✖   3:1   Imports "Options" and "ColorInfo" are only used as types.                                         @typescript-eslint/consistent-type-imports
```

**Comment by sindresorhus** [comment]
Can you do a PR to https://github.com/chalk/chalk/tree/main/source/vendor/supports-color too?

**Comment by silverwind** [comment]
Sure, I can try.

**Comment by silverwind** [comment]
https://github.com/chalk/chalk/pull/603 for vendor update in chalk.

**Pull request merged**
