### PR TITLE
jetbrain ide run

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by Qix-** [comment]
Actually, this could just be

```javascript
forceColor = Boolean(env.FORCE_COLOR.length) && env.FORCE_COLOR !== '0';
```

**Comment by sindresorhus** [comment]
Please include a description of what this solves.

**Comment by bluelovers** [comment]
in jetbrain ide, FORCE_COLOR is 'true'

**Comment by sindresorhus** [comment]
The PR also needs a better title.

**Comment by sindresorhus** [comment]
@Qix- That would only support `"FORCE_COLOR=true"` though. What about `"FORCE_COLOR=false"`? If we support the former, we should support the latter too. And if we go this far, should we also support real booleans `true` and `false` in case people set the env variables inside a Node.js script.?

**Comment by Qix-** [comment]
> What about `"FORCE_COLOR=false"`?

True, didn't think about that.

> And if we go this far, should we also support real booleans true and false in case people set the env variables inside a Node.js script.?

IMO no, `process.env` is a k/v of environment variables which are pretty universally treated as string/string. I think code that expects `process.env` to hold any other types (include code that puts those types in `process.env` to begin with) are violating a contract of sorts.

I'm not even entirely sure about this. I've never seen `FORCE_COLOR=true` before so I'm somewhat in the camp that Jetbrains should fix this. In fact, I rarely (maybe never) see literal `true` or `false` used in environment variables to indicate booleans - it's usually `1` or `0`.

**Comment by sindresorhus** [comment]
> I'm not even entirely sure about this. I've never seen FORCE_COLOR=true before so I'm somewhat in the camp that Jetbrains should fix this. In fact, I rarely (maybe never) see literal true or false used in environment variables to indicate booleans - it's usually 1 or 0.

I agree. I have not seen booleans used for this either.

**Comment by sindresorhus** [comment]
@bluelovers Go open an issue on Jetbrains IDE.

**Pull request closed without merging**
