### PR TITLE
Add support for truecolor in kitty

### PR DESCRIPTION
**Pull request by AprilArcus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you link to some docs about this if possible?

**Comment by sindresorhus** [comment]
And you are sure it does not set any more common environment variable for this? For example `COLORTERM`.

**Comment by Qix-** [comment]
cc @kovidgoyal 👋🏻  Does Kitty term indicate truecolor support using any of the already-supported variables? Or does it really define its own terminfo database entry as indicated by the PR?

**Comment by kovidgoyal** [comment]
What already supported variables? It sets COLORTERM=truecolor. And has setrgbf and
setrgbb in its terminfo. And setaf and setab.

**Comment by Qix-** [comment]
We don't check the terminfo database here, just environment variables. Good to know, thank you!!!

@AprilArcus can you verify that `COLORTERM` is indeed set to `truecolor` and show us a reproduction that this is being ignored?

**Comment by AprilArcus** [comment]
`COLORTERM` is set to `truecolor` on localhost, but that environment variable does not survive when SSHing to a remote host. `TERM` does, however:

```
gnosis% echo $TERM $COLORTERM
xterm-kitty truecolor
gnosis% ssh sophos
Last login: Mon Aug 29 14:02:58 2022 from 172.253.30.65
ril@sophos ~ % echo $TERM $COLORTERM
xterm-kitty
ril@sophos ~ % 
```

**Comment by Qix-** [comment]
Fair enough. To work around this, you could also do `ssh -o SendEnv=COLORTERM`, or [set it up in your ssh_config](https://superuser.com/a/1447790).

**Comment by AprilArcus** [comment]
I don't control `/etc/ssh/sshd_config` on the remote end

**Comment by Qix-** [comment]
That answer is referring to your _local_ ~/.ssh/config` file.

**Comment by AprilArcus** [comment]
> Then on the server, make sure to allow client to pass certain environment variables in your `/etc/ssh/sshd_config` config file:
> ```
> AcceptEnv LANG LC_* FOO BAR*
> ```

**Comment by kovidgoyal** [comment]
You shouldn't rely on env vars for detection. Both sudo and ssh dont pass them through.  I would recommend you turn on truecolor by default and only turn it off with a blacklist for the few terminals that dont support it based on TERM. In 2022 most terminals support it.

@AprilArcus If you use the ssh kittne in kitty, it will apss COLORTERM through ssh magically even without needing to modify sshd_config

**Pull request merged**
