### PR TITLE
Detect 16m color support on Windows >=10.0.14931

### PR DESCRIPTION
**Pull request by partheseas**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you comment a link to a source confirming this?

**Comment by partheseas** [comment]
Yes. Here is the announcement post on Microsoft's development blog.

https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

**Comment by sindresorhus** [comment]
Why close this?

**Comment by partheseas** [comment]
@sindresorhus I honestly have no idea how it got closed, sorry!

**Comment by partheseas** [comment]
@sindresorhus Just curious, when will Chalk be updated to use supports color ^5.0.0?

**Pull request merged**
