### PR TITLE
Add support for "GitLab CI" & "AppVeyor"

### PR DESCRIPTION
**Pull request by gucong3000**
from:
https://www.appveyor.com/docs/environment-variables/
http://docs.gitlab.com/ee/ci/variables/README.html#predefined-variables-environment-variables
https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
https://circleci.com/docs/1.0/environment-variables/#basics
https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you show a screenshot/example of them supporting color in their logs?

**Comment by gucong3000** [comment]
image

GitLab CI

**Comment by gucong3000** [comment]
image
https://ci.appveyor.com/project/gucong3000/gulp-reporter/build/job/4dqfgqihdre4q87h

**Comment by gucong3000** [comment]
I found a expression `env.CI === 'Travis'`, so I read [documet of Travis CI](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables). this expression will always returns false. Should we remove it or replace with expression about [CodeShip](https://codeship.com): `env.CI_NAME === 'codeship'` ?

**Comment by gucong3000** [comment]
May be we should just use `env.CI` to decision
```js
if (env.CI) {
	return 1;
}

```

**Comment by sindresorhus** [comment]
> I found a expression `env.CI === 'Travis'`, so I read [documet of Travis CI](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables). this expression will always returns false. Should we remove it

Yes

> May be we should just use `env.CI` to decision

Not all CI's supports color, so better to have a whitelist I think.

**Comment by gucong3000** [comment]
Travis CI, CircleCI, Gitlab CI, Appveyor and CodeShip use `env.CI`

see: https://github.com/watson/ci-info/blob/master/index.js#L42

**Comment by sindresorhus** [comment]
Hmm, maybe we should just assume CI's support color. The ones I know about does.

**Comment by sindresorhus** [comment]
@Qix- What do you think?

**Comment by gucong3000** [comment]
ANSI color:
- Support by default:
  - Travis CI
  - CircleCI
  - Gitlab CI
  - Appveyor
- Support when install plugin:
  - Jenkins
- unknow by me:
  - CodeShip

**Comment by Qix-** [comment]
I think that's a safe assumption @sindresorhus. We can only do so much to be accurate.

**Comment by gucong3000** [comment]
Should we add a list to define support level for CI?
```js
const ciSupportLevel = {
	TRAVIS: 1,
	CIRCLECI: 1,
	APPVEYOR: 1,
	GITLAB_CI: 1
};
if ('CI' in env) {
	for (const ciName in ciSupportLevel) {
		if (ciName in env) {
			return ciSupportLevel[ciName];
		}
	}
	return 0;
}
```

**Comment by sindresorhus** [comment]
> Should we add a list to define support level for CI?

No, that's too much work to maintain and not much benefit knowing the color level on CIs.

**Comment by Turbo87** [comment]
@sindresorhus could you add a release including this PR?

**Comment by sindresorhus** [comment]
Done

**Pull request merged**
